export const GET_TODO = "GET_TODO";
export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SORT_TODO_ACTION = "SORT_TODO_ACTION";
export const SORT_TODO_ACTION_DESC = "SORT_TODO_ACTION_DESC";
export const SORT_TODO_COMPLETE = "SORT_TODO_COMPLETE";
export const SORT_TODO_INCOMPLETE = "SORT_TODO_INCOMPLETE";
export const DELETE_TODO = "DELETE_TODO";
